import React from 'react';

export const PrivacyPolicy: React.FC = () => (
  <div className="max-w-4xl mx-auto px-4 py-12 prose prose-slate">
    <h1>Privacy Policy</h1>
    <p>Last updated: {new Date().toLocaleDateString()}</p>
    <p>At AI SmartHome Hub, accessible from ai-smarthomehub.com, one of our main priorities is the privacy of our visitors.</p>
    
    <h3>Log Files</h3>
    <p>AI SmartHome Hub follows a standard procedure of using log files. These files log visitors when they visit websites. The information collected includes internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, and referring/exit pages.</p>
    
    <h3>Google AdSense & DoubleClick DART Cookie</h3>
    <p>Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet.</p>
    
    <h3>Affiliate Disclosure</h3>
    <p>We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</p>
  </div>
);

export const TermsOfService: React.FC = () => (
  <div className="max-w-4xl mx-auto px-4 py-12 prose prose-slate">
    <h1>Terms of Service</h1>
    <h3>1. Introduction</h3>
    <p>By accessing this website we assume you accept these terms and conditions. Do not continue to use AI SmartHome Hub if you do not agree to take all of the terms and conditions stated on this page.</p>
    
    <h3>2. AI Generated Content</h3>
    <p>The content provided on this website, including compatibility checks and troubleshooting steps, is generated by Artificial Intelligence. While we strive for accuracy, users should verify critical information with manufacturer manuals.</p>
    
    <h3>3. Limitation of Liability</h3>
    <p>In no event shall AI SmartHome Hub, nor any of its officers, directors and employees, be held liable for anything arising out of or in any way connected with your use of this website.</p>
  </div>
);